"""initial_credit_evaluations_table

Revision ID: 298e0f52a9e9
Revises: 
Create Date: 2026-03-09 00:22:51.438187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '298e0f52a9e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_evaluations', sa.Column('pdf_path', sa.String(), nullable=True))
    op.add_column('credit_evaluations', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_evaluations', 'created_at')
    op.drop_column('credit_evaluations', 'pdf_path')
    # ### end Alembic commands ###
